#'
#' A widget that lets the user upload multiple files (or provide multiple data sources)
#' and concatenates them using a provided expression.
#' Also allows feedback of the current data
#' 

library(shiny)
library(shinyBS)
source("widgetGenericImporter.R")
source("uiHelper.R")

#' Creates an integrating generic importer - a widget that is able to hold multiple data sources
#' and produce output based on an integration function. Also provides callback to the user.
#' 
#' Arguments are the same as in genericImporterInput
#'
#' @param id 
#' @param filetypes 
#' @param importers 
#' @param samples 
#'
#' @return
#' @export
#'
#' @examples
integratingGenericImporterInput <- function(id, filetypes, importers, samples = c()) {
  
  ns <- NS(id)
  
  return(tags$div(class = "integrating-generic-importer",
    genericImporterInput(ns("importer"), filetypes, importers, samples, 
                         reset.button = F,
                         additional.buttons = tagList(
                           actionButton(ns("clear"), "Reset")
                         ),
                         additional.content =  uiOutput(ns("status")),
                         submit.button.text = "Add"
                         )
  ))
}

#' Gets integrated data from integrating generic importer. 
#'
#' exprintegrate: This function generates the output of this control it has following parameters:
#' * data: List of data values to integrate
#' * callback: Function with parameters choices, selected: Changes the list of collected data for user feedback
#'
#' @param input 
#' @param output 
#' @param session 
#' @param exprimport 
#' @param exprsample 
#' @param exprintegrate Generates output data based on the data. 
#'
#' @return Integrated data (produced by exprintegrate)
#' @export
#'
#' @examples
integratingGenericImporterData_ <- function(input, output, session, exprimport, exprsample, exprintegrate) {
  
  variables <- reactiveValues(data = list(), status.choices = c(), status.selected = c())
  importer.data <- genericImporterData("importer", exprimport, exprsample)
  
  # Collect data from generic importer if it's available
  # Store it into it's own array to be able to re-use the importer
  observeEvent(importer.data(), {
    if(!is.null(importer.data())) {
      variables$data[[length(variables$data) + 1]] <- importer.data()
    }
  })
  
  # Clear all data if user clicks clear button
  observeEvent(input$clear, {
    stored.data$data <- list()
  })
  
  # Output the callback from the integration
  output$status <- renderUI({
    
    tag <- tags$div(
      class = "status",
      tags$label(class = "control-label", "Imported data")
    )
    
    choices <- variables$status.choices
    choices.names <- if(is.null(names(choices))) choices else names(choices)
    
    # Have to use numeric for as I cannot preserve that damn name /:
    if(length(choices) > 0) {
      for(i in 1:length(choices)) {
        
        choice <- choices[i]
        choice.name <- choices.names[i]
        
        tag.icon <- if(choice %in% variables$status.selected) icon("check-square-o") else icon("square-o")
        tag <- tagAppendChild(tag, tags$div(tags$span(tag.icon), tags$span(choice.name)))
      }
    }
    tag <- tagAppendChild(tag, tags$div(class = "data-sets",paste(length(variables$data), "data sets loaded.")))
    
    return(tag)
  })
  
  # Define a callback function for integrate
  f.callback <- function(choices, selected) {
    variables$status.choices <- choices
    variables$status.selected <- selected
  }
  
  # The data returned is generated by exprintegrate. It has a callback-function that lets the user see which data has been integrated
  return(reactive({
    
    output <- tryCatch({exprintegrate(data = variables$data, callback = f.callback)}, 
                     error = function(e){
                       showNotification(paste("[Integration] Error:", e), type = "error", duration = NULL)
                       return(NULL)
                     }, 
                     warning = function(w)
                     {
                       showNotification(paste("[Integration] Warning:", w), type = "warning", duration = NULL)
                       return(NULL)
                     })
    return(output)
    
  }))
  
}

#' Gets integrated data from integrating generic importer. 
#' This function is supposed to be called by callModule. Use the one without an underscore for easier access.
#'
#' exprintegrate: This function generates the output of this control it has following parameters:
#' * data: List of data values to integrate
#' * callback: Function with parameters choices, selected: Changes the list of collected data for user feedback
#'
#' @param id 
#' @param exprimport 
#' @param exprsample 
#' @param exprintegrate 
#'
#' @return
#' @export
#'
#' @examples
integratingGenericImporterData <- function(id, exprimport, exprsample, exprintegrate) {
  return(callModule(integratingGenericImporterData_, 
                    id, 
                    exprimport = exprimport,
                    exprsample = exprsample,
                    exprintegrate = exprintegrate
                    ))
}